version: '3'
services:
  producer:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - BOOTSTRAP_SERVERS=pkc-devc19rzw5.us-west-2.aws.devel.cpdev.cloud:9092
     - TOPIC=kafka-spire-test
     - PRINCIPAL=sub
     - SOCKET_PATH=unix:/opt/spire/sockets/workload_api.sock
     - LKC=lkc-devc3mk0gw
